name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE (onefile)
        run: |
          pyinstaller --noconsole --onefile --name ImageCatalog image_catalog_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageCatalog-EXE
          path: dist/ImageCatalog.exe
